name: IngameBBS
version: 1.1.1
main: ink.ltm.ingameBBS.IngameBBS
description: An Ingame BBS
author: Longtianmu
load: STARTUP
api-version: 1.20
permissions:
  ingamebbs.player.*:
    description: "Node for Player Interact a sign"
    default: true
    children:
      ingamebbs.player.info: true
      ingamebbs.player.vote: true